### ISSUE TITLE
docker-compose build -> returned a non-zero code: 64

### ISSUE THREAD

**Issue by thenrion** [quentinfayet/elasticsearch#5]
Hi,
I execute **docker-compose build** and I receive the following errors:
_ERROR: unknown command [-i]. Use [-h] option to list available commands
ERROR: Service 'eddard' failed to build: The command '/bin/sh -c /usr/share/elasticsearch/bin/plugin -i mobz/elasticsearch-head' returned a non-zero code: 64_
Many thanks for this project.

**Comment by quentinfayet** [comment]
Hi thenrion,

On which tag or branch of the project are you trying to execute the `docker-compose build` ?

**Comment by thenrion** [comment]
The master branch.

**Comment by quentinfayet** [comment]
I currently have no problem with the master branch when running `docker-compose build`. 

Could you tell me on which system (Linux, Mac OS, Windows, ...) you are running the command ? Which version of docker and docker-compose you are using, and, if you are running under Windows or Mac OS, which version of boot2docker / docker-tools you are using ?

**Comment by quentinfayet** [comment]
Ok, I got it. The error comes from the version of the elasticsearch image used in the Dockerfile. With the latest version of the image (and thus, the version of Elasticsearch), the way to install plugins has changed. I am fixing it.

**Comment by quentinfayet** [comment]
I fixed the version to `elasticsearch:1.7.3`, because from Elasticsearch 2.0, the way to handle plugins has changed.

Can you give a try to `docker-compose build` after pulling the master branch and tell me if the problem is solved ?

**Comment by thenrion** [comment]
It works perfectly. Thank you very much for your help.

**Comment by quentinfayet** [comment]
My pleasure !
